[2023-05-09T12:47:04.882+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: question1.add_current_time manual__2023-05-09T12:47:02.988492+00:00 [queued]>
[2023-05-09T12:47:04.889+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: question1.add_current_time manual__2023-05-09T12:47:02.988492+00:00 [queued]>
[2023-05-09T12:47:04.889+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-09T12:47:04.897+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): add_current_time> on 2023-05-09 12:47:02.988492+00:00
[2023-05-09T12:47:04.901+0000] {standard_task_runner.py:57} INFO - Started process 1858 to run task
[2023-05-09T12:47:04.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'question1', 'add_current_time', 'manual__2023-05-09T12:47:02.988492+00:00', '--job-id', '504', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpg61unrx4']
[2023-05-09T12:47:04.905+0000] {standard_task_runner.py:85} INFO - Job 504: Subtask add_current_time
[2023-05-09T12:47:04.943+0000] {task_command.py:410} INFO - Running <TaskInstance: question1.add_current_time manual__2023-05-09T12:47:02.988492+00:00 [running]> on host f3950ac719e7
[2023-05-09T12:47:05.002+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='question1' AIRFLOW_CTX_TASK_ID='add_current_time' AIRFLOW_CTX_EXECUTION_DATE='2023-05-09T12:47:02.988492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-09T12:47:02.988492+00:00'
[2023-05-09T12:47:05.003+0000] {sql.py:262} INFO - Executing: insert into records values('2023-05-09 12:47:04.725386')
[2023-05-09T12:47:05.011+0000] {base.py:73} INFO - Using connection ID 'my_postgres_connection' for task execution.
[2023-05-09T12:47:05.048+0000] {base.py:73} INFO - Using connection ID 'my_postgres_connection' for task execution.
[2023-05-09T12:47:05.052+0000] {sql.py:375} INFO - Running statement: insert into records values('2023-05-09 12:47:04.725386'), parameters: None
[2023-05-09T12:47:05.054+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "2023-05-09 12:47:04.725386"
LINE 1: insert into records values('2023-05-09 12:47:04.725386')
                                   ^

[2023-05-09T12:47:05.062+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=question1, task_id=add_current_time, execution_date=20230509T124702, start_date=20230509T124704, end_date=20230509T124705
[2023-05-09T12:47:05.069+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 504 for task add_current_time (invalid input syntax for type integer: "2023-05-09 12:47:04.725386"
LINE 1: insert into records values('2023-05-09 12:47:04.725386')
                                   ^
; 1858)
[2023-05-09T12:47:05.120+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-09T12:47:05.135+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
